# documentation: https://fshschool.org/docs/sushi/configuration/
# 
id: hl7.fhir.us.medication-rems
canonical: http://hl7.org/fhir/us/medication-rems
name: REMS
title: US Medication Risk Evaluation and Mitigation Strategies (REMS) FHIR IG
description: FHIR implementation options and guidance for medication REMS participants
status: draft # draft | active | retired | unknown
version: 2.0.0-ballot
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: STU 2 Ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use | STU1 Ballot
license: CC0-1.0 
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
publisher:
  name: HL7 International / Pharmacy
  url: http://www.hl7.org/Special/committees/medication
dependencies:
  hl7.fhir.us.core:
    id: uscore
    version: 8.0.0
    reason: |
      Defines U.S. EHR expectations on a range of resources that will be passed to and/or queried by REMS CDS servers
  hl7.fhir.uv.smart-app-launch:
    id: SmartAppLaunch
    version: 2.2.0
    reason: |
      Defines base expectations and profiles for SMART app launch requirements
#
#
pages:
  index.md:
    title: REMS IG Home Page
  process.md:
    title: REMS Steps and Terminology
  roles.md:
    title: Participant Roles and Needs
  use-cases.md:
    title: Use Cases
  event-triggers.md:
    title: REMS Interaction Events and Triggers
  future-directions.md:
    title: Future Directions
  credits.md:
    title: Credits
  technical-background.md:
    title: Technical Background
  specification.md:
    title: Formal Specification
  cds-cards.md:
    title: CDS Hooks Card Profiles
  downloads.xml:
    title: Downloads
  change-history.md:
    title: Change History
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative

# menu:
#   Home: index.html
#   Background:
#     Use Cases: use-cases.html
#     Technical: technical-background.html
#   Specification: specification.html 
#   Artifacts: artifacts.html
# 
# 
contact:
  - name: Frank McKinney
    telecom:
      - system: email # phone | fax | email | pager | url | sms | other
        value: frank.mckinney@pocp.com
      - system: email # phone | fax | email | pager | url | sms | other
        value: fm@frankmckinney.com
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: phx
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: draft
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 2
auto-oid-root: 2.16.840.1.113883.4.642.40.34

# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId
#
#
# ╭──────────────────────────────────────────SUSHI flags───────────────────────────────────────────╮
# │  The flags below configure aspects of how SUSHI processes FSH.                                 │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# The FSHOnly flag indicates if only FSH resources should be exported.
# If set to true, no IG related content will be generated.
# The default value for this property is false.
#
# FSHOnly: false
#
#
# When set to true, the "short" and "definition" field on the root element of an Extension will
# be set to the "Title" and "Description" of that Extension. Default is true.
#
# applyExtensionMetadataToRoot: true
#
#
# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
# See the individual option definitions below for more detail.
#
# instanceOptions:
#   Determines for which types of Instances SUSHI will automatically set meta.profile
#   if InstanceOf references a profile:
#
#   setMetaProfile: always # always | never | inline-only | standalone-only
#
#
#   Determines for which types of Instances SUSHI will automatically set id
#   if InstanceOf references a profile:
#
#   setId: always # always | standalone-only
